### ISSUE TITLE
question about the version of pytorch and cuda？

### ISSUE THREAD

**Issue by wangjiwu** [TmacMai/ARGF_multimodal_fusion#1]

**Comment by TmacMai** [comment]
Our Pytorch version is 1.4.0 and CUDA version is 10.1

We also test the code in CUDA 9.0 and Pytorch 1.0.0, and it still works.

**Comment by wangjiwu** [comment]
thanks！  I try it in  Pytorch  1.5.1  and CUDA 10.1.  An error occurred when I was running the code in this environment.   the code run well  in the lower version 👍
